### ISSUE TITLE
Crash: "There was a severe problem during mod loading that has caused the game to fail"

### ISSUE THREAD

**Issue by CircusSeal** [Wabbit0101/mods_hoardercraft#105] opened 2020-04-19 23:41 UTC
Minecraft version 1.12.2

https://gist.github.com/CircusSeal/2d187ba22c9eb3539dfa4c8c365fd799

**Comment by Wabbit0101** [comment] 2020-04-20 12:03
This is usually caused by another mod substituting a vanilla block for its own implementation. Typical culprit is something like Quark substituting the slime block. Check #69 (comment) for solution if you'd like to continue using both mods together. This will be resolved in rewrite of mod for MC-1.14 and later but I'm afraid you'll have to workaround the 1.12 issue w/ the config change.

**Closed as completed by Wabbit0101** 2020-04-20 12:03 UTC
Labels: duplicate, mod_superblocks, incompatibility
