### ISSUE TITLE
Throwing Pinkly Egg Causes Crash 

### ISSUE THREAD

**Issue by JoshD8500** [Wabbit0101/mods_hoardercraft#45] opened 2018-05-28 14:51 UTC
Throwing a Pinkly egg causes the game to crash using latest version of Pinkly sheep

**Comment by Wabbit0101** [comment] 2018-05-30 17:35
I cannot reproduce can you attach a crash report?

**Comment by Wabbit0101** [comment] 2018-06-02 13:32
Fixed in the beta5 release at https://minecraft.curseforge.com/projects/pinklysheep-mod/files/2568543

**Closed by Wabbit0101** 2018-06-02 13:32 UTC
Labels: bug, mod_pinklysheep
