### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by grotefigi** [Wabbit0101/mods_hoardercraft#107] opened 2020-05-11 21:15 UTC
Hello,your mod and this other mod called [Backport] 1.13 Water Mechanics [Bubble Columns] crash if used in the same modpack.I really need both of them,can you please try to make them compatible with eachother please?There are no alternatives for this that I found.Link to the mod: https://www.curseforge.com/minecraft/mc-mods/bubble-column-elevator-backport

**Comment by Wabbit0101** [comment] 2020-05-12 03:30
You'll need to be specific:
- Which of my mods are you referring to?
- What is the error exactly (an "incompatibility" tells me nothing)?..a crash report would be best

**Comment by grotefigi** [comment] 2020-05-13 10:28
I was talking about smart hoppers,i forgot to mentio,sorry,here is the whole crash report.
---- Minecraft Crash Report -------- Minecraft Crash Report ----// There are four lights!
Time: 5/11/20 2:45 AMDescription: Initializing game
java.lang.IllegalArgumentException: Valid output item stacks are required at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes$SimpleRecipes.addRecipe(SmartHopperRecipes.java:548) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes.addRecipe(SmartHopperRecipes.java:740) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes.addStorageRecipe(SmartHopperRecipes.java:777) at org.jwaresoftware.mcmods.smarthoppers.core.SmartVanilla.addStorageRecipes(SmartVanilla.java:116) at org.jwaresoftware.mcmods.smarthoppers.core.SmartVanilla.earlyrecipes(SmartVanilla.java:78) at org.jwaresoftware.mcmods.smarthoppers.runtime.SmartHoppersRuntimeSkeleton.initRecipesSupport(SmartHoppersRuntimeSkeleton.java:410) at org.jwaresoftware.mcmods.smarthoppers.runtime.SmartHoppersRuntimeSkeleton.afterItemsRegistered(SmartHoppersRuntimeSkeleton.java:132) at org.jwaresoftware.mcmods.smarthoppers.runtime.ImplRegisterModObjects.doItemsRegister(ImplRegisterModObjects.java:29) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_ImplRegisterModObjects_doItemsRegister_Register.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850) at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:---------------------------------------------------------------------------------------
-- Head --Thread: Client threadStacktrace: at org.apache.commons.lang3.Validate.isTrue(Validate.java:158) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes$SimpleRecipes.addRecipe(SmartHopperRecipes.java:548) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes.addRecipe(SmartHopperRecipes.java:740) at org.jwaresoftware.mcmods.smarthoppers.core.SmartHopperRecipes.addStorageRecipe(SmartHopperRecipes.java:777) at org.jwaresoftware.mcmods.smarthoppers.core.SmartVanilla.addStorageRecipes(SmartVanilla.java:116) at org.jwaresoftware.mcmods.smarthoppers.core.SmartVanilla.earlyrecipes(SmartVanilla.java:78) at org.jwaresoftware.mcmods.smarthoppers.runtime.SmartHoppersRuntimeSkeleton.initRecipesSupport(SmartHoppersRuntimeSkeleton.java:410) at org.jwaresoftware.mcmods.smarthoppers.runtime.SmartHoppersRuntimeSkeleton.afterItemsRegistered(SmartHoppersRuntimeSkeleton.java:132) at org.jwaresoftware.mcmods.smarthoppers.runtime.ImplRegisterModObjects.doItemsRegister(ImplRegisterModObjects.java:29) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_ImplRegisterModObjects_doItemsRegister_Register.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850) at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252) at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
-- Initialization --Details:Stacktrace: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) at net.minecraft.client.main.Main.main(SourceFile:123) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_251, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 129277152 bytes (123 MB) / 268435456 bytes (256 MB) up to 8589934592 bytes (8192 MB) JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
| State | ID                  | Version      | Source                                            | Signature | |:----- |:------------------- |:------------ |:------------------------------------------------- |:--------- | | LCH   | minecraft           | 1.12.2       | minecraft.jar                                     | None      | | LCH   | mcp                 | 9.42         | minecraft.jar                                     | None      | | LCH   | FML                 | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar                     | None      | | LCH   | forge               | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar                     | None      | | LCH   | smarthoppers        | 4.1.5        | smarthoppers-mc1.12.2-4.1.5.jar                   | None      | | LCH   | 113_water_mechanics | 1.0.2        | WaterMechanicsBackport-1.0.3-1.12.2-NETHERFIX.jar | None      |
Loaded coremods (and transformers):  GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016' Renderer: 'ASUS Radeon RX 470 Series' Launched Version: 1.12.2-forge1.12.2-14.23.5.2847 LWJGL: 2.9.4 OpenGL: ASUS Radeon RX 470 Series GL version 4.6.13587 Compatibility Profile Context 20.4.2 26.20.15029.27016, ATI Technologies Inc. GL Caps: Using GL 1.3 multitexturing.Using GL 1.3 texture combiners.Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.Shaders are available because OpenGL 2.1 is supported.VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes Is Modded: Definitely; Client brand changed to 'fml,forge' Type: Client (map_client.txt) Resource Packs: 1.12-Dokucraft-TSC-High.zip Current Language: English (US) Profiler Position: N/A (disabled) CPU: 12x AMD Ryzen 5 1600 Six-Core Processor

**Comment by grotefigi** [comment] 2020-05-13 10:28
For that crash report I only loaded the two mods

**Comment by Wabbit0101** [comment] 2020-05-13 20:55
Unfortunately, the problem is that the other mod is replacing the vanilla magma and soulsand blocks with its own custom blocks (it says so right on it's CurseForge page). The 1.12 SmartHoppers cannot find the vanilla blocks for its recipes and stops. Unfortunately, these two mods are just incompatible for mc-1.12. I recommend you remove SmartHoppers if you need the functionality of the other mod.

**Comment by Wabbit0101** [comment] 2020-05-15 16:51
Marking closed as it's not-fixable for the mc-1.12 version of SmartHoppers.

**Closed as completed by Wabbit0101** 2020-05-15 16:51 UTC
Labels: mod_smarthoppers, incompatibility
