### ISSUE TITLE
Having some issues with VanillaFoodPantry tools

### ISSUE THREAD

**Issue by craft90** [Wabbit0101/mods_hoardercraft#91] opened 2020-01-05 16:29 UTC
I ran into an issue in the 1.14.4 modpack Limitless by nexusproject regarding the Cutter from your mod. I did report it on their Issue tracker aswell but they asked me to take mod specific bugs to their mod developers.

The issue is that when I'd try to use it in a vanilla crafting table I only get one use out of the cutter before it "goes away". It just disappears and trying to get more crafts out of it leads to both output and input item to disappear or dupe. Which shouldn't happen... it should just take away some durability. I have 10 GB of RAM dedicated to Minecraft so I shouldn't be a lag issue, I don't think. The issue is only for the 3x3 crafting grid, not the 2x2. There it works as intended. There are no CraftTweaker scripts that should affect Vanilla Food Pantry that I can see either.

This occurred with bit o' heat (from charcoal), chicken bits, leather piece.

**Comment by Wabbit0101** [comment] 2020-01-06 01:27
Please include what version of the mod and FORGE that you're using. Your config file also. Otherwise, I can't begin to help.

**Comment by craft90** [comment] 2020-01-06 01:46
MC version 1.14.4
Vanilla food pantry version 5.0b4. , 
Forge version 28.1.107. 
Version 1.08a of TNP Limitless (modpack)

It wouldn't allow me to upload the config. So I opened it with Notepad++ and copied everything into a regular text file.

[vanillafoodpantry-config.txt](https://github.com/Wabbit0101/mods_hoardercraft/files/4024391/vanillafoodpantry-config.txt)

**Comment by Wabbit0101** [comment] 2020-01-08 18:44
I am unable to reproduce this problem in an environment with just VFP and the lastest Forge build for 1.14.4. I can also produce "disappearing items" in a crafting grid in the modpack that are plain vanilla items (eg. put a damaged hoe in the grid and just move it around from slot to slot...it magically disappears after a few moves). Also note that this crafting grid is not vanilla GUI (there are a couple crafting grid and player inventory tweak mods in the pack).

Outside of the modpack, both the flint cutter and flint butcher axe work as intended (they receive 1 damage pt for each crafting use). I won't close this issue just yet, but unless you can narrow this problem down to VFP+**???** mod incompatibility there isn't much I can do. This pack has 100's of mods and I've got a potato computer so just starting the pack up takes 10mins.

**Comment by craft90** [comment] 2020-01-08 18:50
I suppose it's a modpack issue then. Not surprised to be honest. 1.14. is unstable already in vanilla, add a hundred mods and it's bound to be some issues. I'll see if the modpack developer has better luck nailing it down. Thanks for taking your time anyway and I apologize for wasting your time.

**Comment by Wabbit0101** [comment] 2020-01-08 19:02
I'm preparing a VFP release soon so I will do more thorough testing on the grid/recipes. Things changed a lot for 1.14 for modded recipes so there might be something; who knows. But so far, I can't trigger disappearing items or dups with the RB or the forge-1.14.4-28.1.111 dev build, so it may be an incompatible mod interaction that's going to be hard to pin down outside the modpack.

**Comment by Wabbit0101** [comment] 2020-04-29 14:12
I've not seen this issue with the 1.15.2 version of the mod and no one else is reporting the issue (standalone) in the 1.14.4 version. Closing as I don't think it's a VFP-originated issue.

**Closed as completed by Wabbit0101** 2020-04-29 14:12 UTC
Labels: mod_vanillafoodpantry, can't reproduce
